### ISSUE TITLE
Condition when it can't connect to Stripe API

### ISSUE THREAD

**Issue by MordantWastrel** [jcberquist/stripe-cfml#17]
We are starting to implement this library into one of our applications and it will save us a ton of time. Thank you!

In working out the success/error states for Stripe API calls, I ran one test where it couldn't connect to api.stripe.com (by blocking the connection on my end). It throws an error line 96 of stripe.cfc:

`  response[ 'requestId' ] = rawResponse.responseheader[ 'Request-Id' ];`

Because `Request-Id` doesn't exist.

There doesn't appear to be any handling for if the connection just fails outright. 

This is obviously pretty unlikely but since we're pretty new to this project, I'm curious whether this is an intentional choice or something that just hasn't been got round to?

**Comment by jcberquist** [comment]
This is something I just haven't gotten to. I have encountered this error in production (i.e. it is unable to connect to the Stripe API), but it has been so rare that I haven't been impelled to do something more about it.

**Comment by MordantWastrel** [comment]
If you want to provide any guidance on how you'd like it handled (e.g. a `throw` versus returning certain values) I would be happy to tackle it.

**Comment by jcberquist** [comment]
Thanks! I think I would prefer to have it throw an error when there is a connection failure rather than return something, since the fields it normally returns don't really make sense in such a case.

**Comment by MordantWastrel** [comment]
A custom error type like `StripeConnectionError` or just a general CF application error?

**Comment by jcberquist** [comment]
A custom type would be nice so it can be easily handled separately if desired.

**Comment by MordantWastrel** [comment]
Done and tested in my local setup. I had a quick look at the test suite and it looks like it might need a new spec that doesn't mock the result. I ran out of time today but can get to this later in the week if you want to keep this open.

**Comment by jcberquist** [comment]
Thanks for doing this. Like I said in the pull request, if you want to add a test, I will take it, but I don't feel strongly about it in this case.
