### ISSUE TITLE
Stripe 3rd party library list doesn't include stripe-cfml!

### ISSUE THREAD

**Issue by MordantWastrel** [jcberquist/stripe-cfml#19]
Technically an issue with them and not with this project, but probably it would help if you reached out to them (rather than us)

https://stripe.com/docs/libraries#community

It lists two much older CFML libraries but not this one!

**Comment by jcberquist** [comment]
Yeah, this is true 😄. However, most of those libraries in the community section look out of date to me. I don't really feel motivated to try and get my library listed there.
