### ISSUE TITLE
rawResponse.status_code Errors out Line 95 on Stripe.cfc

### ISSUE THREAD

**Issue by GiancarloGomez** [jcberquist/stripe-cfml#21]
The key I am receiving is rawResponse.statuscode not rawResponse.status_code, I made the change on my local file and it works

**Comment by jcberquist** [comment]
This is fixed in `v2.3.1`.

**Comment by GiancarloGomez** [comment]
@jcberquist Sorry I did not push a fix, got slammed and was meaning to get back to it. Thank you!

**Comment by jcberquist** [comment]
No worries, thanks for reporting the issue!
