### ISSUE TITLE
Stripe Signature throws - exceptionType

### ISSUE THREAD

**Issue by MordantWastrel** [jcberquist/stripe-cfml#23]
Would you consider adding a special exception type for the `throw` errors in `webhooks.cfc`?

We'd like to be able to catch errors specific to different types of failures, including webhook signature failures, rather than having them go to the general exception handler. 

Something like `StripeSignatureException`?

**Comment by jcberquist** [comment]
That sounds reasonable to me.

**Comment by jcberquist** [comment]
I added a type to those exceptions in `v2.3.1` - they now throw a `StripeSignatureVerificationException` - This matches the Java SDK with the addition of `Stripe` at the beginning, which seemed reasonable to me.
