### ISSUE TITLE
Metadata for subscription schedule - items, unit_amount

### ISSUE THREAD

**Issue by MordantWastrel** [jcberquist/stripe-cfml#24]
The metadata in `subscription_schedule.json` looks like this:

```
{
    "canceled_at": "datetime",
    "completed_at": "datetime",
    "created": "datetime",
    "phases": {
        "billing_thresholds": {
            "amount_gte": "currency"
        },
        "start_date": "datetime",
        "trial_end": "datetime"
    },
    "released_at": "datetime"
}
```

But the subscription schedule "phases" block takes an `items` array: https://stripe.com/docs/api/subscription_schedules/create#create_subscription_schedule-phases-items

`items` can take an optional `price_data` struct which has a `unit_amount` or `unit_amount_decimal` argument. These are not labeled as currency in the metadata and so (I think) are not being multiplied correctly if `convertToCents : true`.

**Comment by jcberquist** [comment]
Thanks for the report. The metadata in question is found in `lib/resources/subscriptionSchedules.cfc`. It looks to me like the `subscription_schedule` object doesn't directly price_data, but rather price objects. So if you include price data when creating the schedule, new price objects are created. I haven't done this is practice however, so I could be mistaken.
