### ISSUE TITLE
discount_amounts convertToCents in invoice line items

### ISSUE THREAD

**Issue by MordantWastrel** [jcberquist/stripe-cfml#26]
Similar to #24 - If you create an invoice line item with a discount, create an invoice with that pending item, and then retrieve that invoice, stripecfml does not convert the `amount` field in the discount array, such that a discount of $4.64 shows up like this:

![image](https://user-images.githubusercontent.com/11874518/95771543-d8f1bb00-0c80-11eb-980a-1af48dc32bed.png)

I can likely look at your fix for #24 and figure this out but was heading out the door and wanted to post it while I had it in front of me.

**Comment by jcberquist** [comment]
Thanks, this should be fixed in `v2.4.1`
