### ISSUE TITLE
Currency format metadata: credit notes

### ISSUE THREAD

**Issue by MordantWastrel** [jcberquist/stripe-cfml#27]
More from the 'fields that are currency responding to `convertToCents` department:

https://stripe.com/docs/api/credit_notes/create

 The possible currency values for this action are:

* `credit_amount`
* `out_of_band_amount`
* `refund_amount`

I think those are working, even though I only see `amount` in the metadata. But if you issue a credit note using the `lines` property, the child parameters are not being converted:

* `amount`
* `unit_amount`
* `unit_amount_decimal`

Right now if I try to issue a credit note with a `refund_amount` of 15 and `lines` whose `unit_amount_decimal` adds up to 15, I will get this error: 

```
The sum of credit amount, refund amount and out of band amount ($15.00) must equal the credit note amount ($0.15). 
```

**Comment by MordantWastrel** [comment]
It seems like the solution should be to edit `metadata/credit_note.json`:

```
{
    "amount": "currency",
    "credit_amount" : "currency",
    "out_of_band_amount" : "currency",
    "refund_amount" : "currency",
    "created": "datetime",
    "lines" : {
        "amount" : "currency",
        "unit_amount" : "currency",
        "unit_amount_decimal" : "currency"
    }
}
```

But that doesn't seem to have any effect. Happy to get this into a PR if you can nudge me in the right direction.

**Comment by jcberquist** [comment]
So the `metadata` folder is used for parsing the "objects" that the API returns - these don't always line up with how you send data _to_ the API. The metadata that is used for sending data to the API is in the resource components themselves.

In this case that would be here: [creditNotes.cfc#L6-L10](https://github.com/jcberquist/stripe-cfml/blob/master/lib/resources/creditNotes.cfc#L6-L10). What is needed is to add the "lines" metadata you have above there.

For the data returned from Stripe, it looks to me like there is actually a [credit_note_line_item](https://stripe.com/docs/api/credit_notes/line_item) object that should be added to the `metadata` folder.

**Comment by MordantWastrel** [comment]
I will get a partial PR up tonight or tomorrow. I have the credit_note_line_item metadata JSON file but I'm not sure where to reference it after adding it.

**Comment by jcberquist** [comment]
It doesn't need to be referenced anywhere, Stripe always includes a "type" key in the objects they return, and that is used to find the appropriate metadata file.

**Comment by jcberquist** [comment]
`v.2.4.2` is out with your fixes included. Thanks again.
