### ISSUE TITLE
using stripe.checkout.sessions.create

### ISSUE THREAD

**Issue by pilere** [jcberquist/stripe-cfml#30]
Hi,
I try to use stripe-cfml to bill one time payment AND subscription ... but I cannnot invoque stripe.checkout.sessions.create with success url  ... is this library late on the stripe SDK ?

Stéphane

**Comment by jcberquist** [comment]
Hi, I am sorry you are having issues, but it is not clear to me exactly what is going on. Are you getting an error message back from the Stripe API when calling `stripe.checkout.sessions.create()`?

**Comment by andreasRu** [comment]
Just wanted to post that just yesterday I've made my first test using stripe cfml in my stand alone environment to use `stripe.checkout.sessions.create()`. It worked wonderfully, really!!! Didn't know it would be that freaking easy. Took more time to setup my stripe account and go through stripes docs than making this module work. Everything  worked so smooth and well. 

@jcberquist: I'd say, you can close this issue, if there are still any issues, the original poster should re-open it and specify the specifc stack trace and submit more detailed information about his issue.

Again, thx for this great libary!!!
