### ISSUE TITLE
Is this codebase SCA ready?

### ISSUE THREAD

**Issue by agentfitz** [jcberquist/stripe-cfml#31]
Hey guys, I built an application a long time ago using the old Stripe.cfc by James Eisenlohr which has been working great. But it appears to interact with Stripe API V1, which I'm guessing is not [Strong Customer Authentication](https://support.stripe.com/questions/strong-customer-authentication-(sca)-preparation-and-resources) (SCA) compatible.

**Is this `stripe-cfml` library "SCA compatible?"**

I ask because the owner of the company I work for received an ominous message about how much money they could be losing if we don't upgrade our implementation to work with the new PaymentIntents API (and other APIs) which are apparently equipped for SCA use.

Thanks for any guidance on this.

**Comment by jcberquist** [comment]
I guess it depends on what you mean 😄 - yes, you can interact with the PaymentIntents API endpoint as well as the other SCA compatible APIs with this library, and in fact I use this library to do just that, but your flow for handling payments will probably/possibly need to be changed, which will take some work on your part. 

See also #12
