### ISSUE TITLE
Append method was not found

### ISSUE THREAD

**Issue by Codepwned2** [jcberquist/stripe-cfml#34]
Heyo, 

When attempting to use the method: stripe.checkout.sessions.create(); I keep getting this error. I'm on a fully updated local ColdFusion 2018 version. Normal setup. No custom tags etc. 

The append method was not found.
Either there are no methods with the specified method name and argument types or the append method is overloaded with argument types that ColdFusion cannot decipher reliably. ColdFusion found 0 methods that match the provided arguments. If this is a Java object and you verified that the method exists, use the javacast function to reduce ambiguity.

The error occurred in D:/.../cfc/Stripe/stripe.cfc: line 69
Called from D:/.../cfc/Stripe/lib/apiResource.cfc: line 31
Called from D:/.../w/pay.cfm: line 36
Called from D:/.../application.cfc: line 121
67 :         }
68 : 
69 :         sources.params.append( argOverrides, true );
70 : 
71 :         // path

**Comment by jcberquist** [comment]
Could you show me how you are calling `stripe.checkout.sessions.create()`? That is, are you calling it with named arguments or positional arguments?  Could you give me an example of the arguments you are using?

**Comment by Codepwned2** [comment]
John, 

I realized what was happening yesterday and completely forgot to update this issue. The information being sent through the function was accidentally a sample of the response you get from Stripe, and was creating an incorrect error by ColdFusion. Since I rarely work with ColdFusion in CFScript, I didn't realize issues like this can occur. 

Please mark this issue as a non-issue. I've even reached out to Zach at Stripe to suggest they include this on their code api support page. It's worked solidly for everything I've tried and much better than the two older cfml to stripe api tools I found.

**Comment by jcberquist** [comment]
Alright, thanks for the update!
