### ISSUE TITLE
Request-Id doesn't exist

### ISSUE THREAD

**Issue by MordantWastrel** [jcberquist/stripe-cfml#38]
Once in a blue moon, we get the following error when submitting a paymentIntent create to Stripe:

```
expression Error: key [Request-Id] doesn't exist 
  File "modules/stripecfml/stripe.cfc", line 105, in call
    response[ 'requestId' ] = rawResponse.responseheader[ 'Request-Id' ];
  File "modules/stripecfml/lib/apiResource.cfc", line 31, in onMissingMethod
    metadata.methods[ missingMethodName ]
  File "modules_app/invoices/models/requestObjects/createTransaction.cfc", line 136, in process
    );
  File "modules_app/invoices/models/qPaymentGatewayClient.cfc", line 412, in sendCardToGateway
    return transactionRequest.process( gateway = this );
  File "modules_app/invoices/models/qPaymentGatewayClient.cfc", line 381, in processCard
    return sendCardToGateway( argumentCollection = arguments );
  File "model/service/EventService.cfc", line 1098, in processEventPaymentFromForm
    var result = gateway.processCard( orderType = 'sale', invoiceNo = invoiceNo, transactionRequest = paymentRequest );
```

`createTransaction.cfc` is our request object where we assemble everything needed for the request. The lines in question:

```
	var response = stripe.paymentIntents.create(
			params = this.transformRequest(),
			headers = {
				'stripeAccount' : gateway.getVendorProps()[ "loginID" ],
				'idempotency_key' : this.getidempotency_key()
			}
		);
```

That this happens so rarely tells me it may just be a hiccup with the Stripe API - but the error handler isn't capturing the HTTP result to see exactly what we did get back.

Can we (or is there already) a way to wrap this in a try/catch so we can throw a specific exception when a Stripe API call fails and dump out the result?

on stripe-cfml v2.8.0 if it makes a difference!

**Comment by jcberquist** [comment]
Good idea, I don't want to lose the details of the request even if the request id is missing. I am not sure, do you think you would you prefer to still get an exception, just with better request response information, or just not supply the requestId struct key in a response when it is missing? I am inclined to still throw an exception myself, but am open to persuasion. If an exception is thrown, how would you like it to preserve the information that was returned from Stripe?

**Comment by jcberquist** [comment]
Also, unfortunately, you look to be a person using the format I removed in v3+ 😞 (see #37) how bad is it going to be to update away from using `params =` and `headers =` in your code base?

**Comment by MordantWastrel** [comment]
I would try to catch it in your library and assign the response object to the CF error struct and then re-throw it, so that whatever error handlers people like us have in place will continue to work but just have more relevant information.

Regarding #37 - it's enough work that we've held off upgrading, but not so much that it's unmanageable. I think I just need to be more clear on how we're supposed to do it instead and simply haven't had a day to set aside and work through it.

**Comment by redtopia** [comment]
I encountered this issue today when trying to delete an account that doesn't exist. The call I made was:
```
response = stripe.accounts.delete(
    'acct_1KM3gJRohkf08NDd'
);
```

I made the following change on line 108 of stripe.cfc to fix it:

```
response[ 'requestId' ] = rawResponse.responseheader.keyExists( 'Request-Id' ) ? rawResponse.responseheader[ 'Request-Id' ] : '';
```

**Comment by redtopia** [comment]
@jcberquist, in the example I gave above, it appears that your change would prevent me from seeing the response as a struct, which contains more relevant information about the error than the exception you are throwing. Here's what it looks like when you set the Request-Id to an empty string instead of throwing an error:

![image](https://user-images.githubusercontent.com/812777/151438785-e8d2a909-cf96-4de3-8958-80c9988a2b08.png)

**Comment by jcberquist** [comment]
As I noted above, I include the response in the extendedInfo of the exception. It didn't seem to me that proceeding when the request id was missing was a good idea, as every response from the API is supposed to include this. In fact I have encountered this error, and I went and checked and Stripe had no record of the request on their end as far as I could see, so it is though it didn't happen. 

However, you are right to point out that not all error responses will have it. Other SDKs throw error exceptions in cases such as the above. So I should probably either throw an API error exception in such cases or pass error responses back without a RequestId.

**Comment by jcberquist** [comment]
Alright, in `v3.2.1` the error will only be thrown when a 200 level response is missing the `Request-Id` header. If it is an error response from Stripe and there is no `Request-Id` then the response struct will just not have the `requestId` key. 

It will be interesting to see if it is possible to get a 200 level response with no `requestId`. And I still need to decide if more should be done to handle error responses from the API as opposed to just passing them through.

**Comment by redtopia** [comment]
Got it... seems to me that in this case the error is already being reported by the stripe api and any app would therefore be able to handle the error consistently. By throwing an error, you're forcing the caller to deal with the error in a different way.
