### ISSUE TITLE
JSON parsing failure: Unexpected end of JSON string

### ISSUE THREAD

**Issue by stevednicola** [jcberquist/stripe-cfml#39]
<cfscript>   
	stripe = new cfcs.stripecfml.stripe("pk_test_XXXXXXXXXXXXXXXXXX");

	card =  { number = "4242424242424242", exp_month = 5, exp_year = 2016 };
	charge = stripe.createCharge( amount = 2000, card = card );
	writeDump( charge );

</cfscript>   

I get this error:
JSON parsing failure: Unexpected end of JSON string
154 :                 .listFirst( '.' ) 155 :                 .replace( '/', '.', 'all' ); 156 :             metadata[ metaName ] = deserializeJSON( fileRead( path ) ); 157 :         } 158 :         return metadata;

I installed the stripecfml folder in my cfcs directory. I am guessing that is what is wrong. 

Thank you in advance for any help you can offer.

**Comment by jcberquist** [comment]
Have you checked in the metadata folder to ensure that all of the files are present and correct there? It would be helpful to know which file in particular was causing that error. Could you try wrapping those lines in a try/catch and then dumping out the file path to the offending file when it errors?

**Comment by stevednicola** [comment]
***@***.***

I think I have it installed correctly. I would be willing to pay you for your time to help me get this up and running.

sn

**Comment by jcberquist** [comment]
Hi, I am sorry, I don't have time to work on this directly. You might try a company like Ortus Solutions who I am sure could help you. That said, if I were you, I would try to chase this error down myself a little bit. For example, try changing the `loadMetadata()` function:
```cfscript
private struct function loadMetadata( required string basePath ) {
    var metadataPath = basePath & 'metadata/';
    var metadata = { };
    var jsonFiles = directoryList( metadataPath, true, 'path', '*.json' );
    for ( var path in jsonFiles ) {
        var metaName = path
            .replace( '\', '/', 'all' )
            .replace( metadataPath, '' )
            .listFirst( '.' )
            .replace( '/', '.', 'all' );
        try {
            metadata[ metaName ] = deserializeJSON( fileRead( path ) );
        } catch (any e) {
            writeDump( path );
            writeDump( fileRead( path ) );
            abort;
        }
    }
    return metadata;
}
```
Then try your test code again. When it errors, you can see which file it errored on, where it thinks that file is, and what the contents of the file are. That should go a long ways towards solving this.

**Comment by stevednicola** [comment]
Missing content in file... upload error of some sort.
