### ISSUE TITLE
Error when retrieving account info: The function [append] does not exist in the String

### ISSUE THREAD

**Issue by redtopia** [jcberquist/stripe-cfml#41]
Retrieving account information using `stripe.accounts.retrieve(stripeConnectAccountID);` fails with the error:
```
The function [append] does not exist in the String
```

This is because I am not using named arguments. The [stripe documentation](https://stripe.com/docs/api/accounts/retrieve?lang=node) doesn't show a named argument, and `stripe.accounts.delete(stripeConnectAccountID);` works, so it's not clear that I need to add one.

Looking at `/stripe.cfc` on line 70, the code assumes that `sources.params` is a struct, which is why this exception occurs.

I also noticed that the `getSources()` function always returns a struct with two keys: `params` and `headers`, and in the case when the caller is using positional args, the `params` value could be any type. The way I was making the call, it was a string, not a struct as was expected. I didn't dig deep enough to figure out why this works with `account.delete`.

To fix the error, I figured out that I need to call it like this:

```
stripe.accounts.retrieve(account_id=r.stripeConnectAccountID);
```

**Comment by jcberquist** [comment]
Thanks, `stripe.accounts.retrieve()` is actually a custom method that is supposed to support both passing an `account_id` and also being called with no arguments. So it is handled differently than other methods. It should now handle your situation correctly in `v3.2.0`.
