### ISSUE TITLE
Format for the Webhooks

### ISSUE THREAD

**Issue by nzflew** [jcberquist/stripe-cfml#43]
Hi,

I am just having an issue when calling the following for the stripe webhook

<cfset event = application.stripe.webhooks.constructEvent(webhookJSONPayload, stripeSignatureHeader, endpointSecret) />

each of the values I am returning are as follows

<cfset endpointSecret = 'whsec_?????' />
<cfset webhookJSONPayload = toString(getHttpRequestData().content) />
<cfset requestHeaders = getHttpRequestData().headers />
<cfset stripeSignatureHeader = StructFind(requestHeaders, 'stripe-signature') / >

I get an error "No signatures found matching the expected signature for payload". I am wondering if this is an issue with how I am returning the payload or the signature. Any help or pointers would be appreciated, this is the final bit of the puzzle for me to get a subscription up and running.

Great work on the library as well.

nzflew

**Comment by jcberquist** [comment]
Hmm, it is difficult to say from just what you have why the signatures aren't matching. I guess I would start by verifying you are passing the right information into the method. How are you retrieving the `webhookJSONPayload` and the `stripeSignatureHeader`?

**Comment by jcberquist** [comment]
To expand on the above, if you are using a framework, it might make the incoming request body and headers available to you in some way. But if not you need to use `getHTTPRequestData()`; the resulting struct will contain the request `content` (i.e. the `webhookJSONPayload`) and the request `headers`, from which you can get the stripe signature header (i.e. the `stripeSignatureHeader` above).

**Comment by nzflew** [comment]
Thanks John,

The stripe signature I am returning is like this -
t=1645599762,v1=a4f346a71f6792f9c1e64c7d0a4e91765111d9ad3054832823e799bc530d45ca,v0=e8dd64a4613cb96477e1ff9208ea6f0f6cd28c5e7775274964315233cb4de92c

The payload I am getting with - <cfset variables.requestContent =
toString(getHttpRequestData().content) />

I am wondering if it is the formatting of the payload I am trying to pass
into constructEvent.
I am able to get all the data I need out of the payload for other things, I
just didn't know if there was something specific out of the payload to dump
into the constructEvent or whether it is the whole thing.

If you can confirm whether <cfset payload =
toString(getHttpRequestData().content) /> is what you would normally use to
get the payload I will continue testing at my end.

Mark

**Comment by jcberquist** [comment]
`getHttpRequestData().content` should be correct for the payload. The signature you show looks correct as well.

**Comment by knittingguy** [comment]
@nzflew To use webhooks, you need to include the endpoint secret key in the settings.  The endpoint secret key starts with whsec_ in the key string.
