### ISSUE TITLE
isInteger() causes an exception to be thrown when validating cents.

### ISSUE THREAD

**Issue by redtopia** [jcberquist/stripe-cfml#44]
I am changing my money values to integers by multiplying by 100 and then sending them to the Stripe API, which is what Stripe expects. Some values, however, cause stripe-cfml to throw an exception when isInteger() fails. Here's a quick snippet that shows it fail:

	function isInteger( required any varToValidate ) {
		return ( isNumeric( arguments.varToValidate ) && isValid( 'integer', arguments.varToValidate ) );
	}
	cents = JavaCast("integer", 17.10 * 100);
	writeOutput(isInteger(cents)); // will return false

I can workaround the issue by calling JavaCast("integer", cents).

Looking into the issue further, both Lucee and ACF have issues with `isValid("integer", cents)`

The following code will demonstrate the problem more clearly... some values are valid, others are not.

    for (i = .01; i < 1; i += .01) {
        x = 17 + i;
        xInt = x * 100;
        writeoutput("<p>isValid('integer', #xInt#) = #isValid('integer', xInt)#</p>");
    }

For now I will just call JavaCast() prior to making API calls, but it seems like perhaps the isInteger() function needs to take into consideration this issue.

I also submitted a Lucee bug report here: https://luceeserver.atlassian.net/browse/LDEV-3926

**Comment by jcberquist** [comment]
This is a consequence of floating point math. That is why when this library converts dollar amounts under the hood it uses rounding: [lib/parsers/arguments.cfc#L119](https://github.com/jcberquist/stripe-cfml/blob/master/lib/parsers/arguments.cfc#L119). So I do think the `isInteger()` method is working correctly, it is just that the floating point math you are doing sometimes results in non-integer results - so I believe the solution is to ensure you are actually passing in an integer, and that this is not an issue with the method itself.

**Comment by redtopia** [comment]
Ok... I figured it would be best to document it somehow. The math that my code is executing is exactly what I wrote above, which any programmer would think should just work. But you're right, it is a known issue with floating point math with CFML. However, I would argue that letting the stripe api handle the validation would be better.
