### ISSUE TITLE
Upcoming Stripe feature: Invoice Revisions

### ISSUE THREAD

**Issue by MordantWastrel** [jcberquist/stripe-cfml#45]
We use Stripe invoices a lot and had requested a feature that would allow us to revise an invoice after it's been finalized but before it's been paid. They've added this feature in beta and have invited us to test it out.

I can either ask them to add @jcberquist as well or just report on it and the relevant syntax on this issue if you (we) want to get a head start adding it to stripe-cfml. Do you have a preference?

**Comment by jcberquist** [comment]
Hi @MordantWastrel, I dealt with something like this once before (#16). I am happy to just have you create a PR for the new syntax and I will merge it in.

**Comment by MordantWastrel** [comment]
FWIW, we stopped using Stripe invoices due to the additional fees so we won't be submitting a PR for this anytime soon, but it looks pretty straightforward if anybody else wants to!
